version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Australia/ACT
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis.clients:jedis
    versions:
    - 3.5.1
    - 3.5.2
  - dependency-name: org.checkerframework:checker-qual
    versions:
    - 3.10.0
    - 3.11.0
    - 3.9.1
  - dependency-name: net.kyori:adventure-api
    versions:
    - 4.4.0
    - 4.5.0
    - 4.5.1
    - 4.6.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
