format: <{DISPLAYNAME}> {MESSAGE}

#groupFormat:
#  default: <{DISPLAYNAME}> {MESSAGE}

groupColors:
   default: f

channels:
  BCast:
    format: '&6[&4Broadcast&6] &a{MESSAGE}'
    command: bcast
    permission: bungeechat.broadcast
    permission-listen: '*'
#  ModChat:
#    format: '[ModChat] <{DISPLAYNAME}> {MESSAGE}'
#    command: mc
#    permission: someperm.modchat