name: BungeeChatBukkit
version: ${pom.version}

main: au.com.addstar.bc.BungeeChat

softdepend: [Vault]

permissions:
  bungeechat.color:
    default: op
  bungeechat.format.*:
    default: op
    children:
      bungeechat.format.reset: true
      bungeechat.format.bold: true
      bungeechat.format.italic: true
      bungeechat.format.underline: true
      bungeechat.format.strikethrough: true
      bungeechat.format.magic: true
    
  bungeechat.format.reset:
    default: op
  bungeechat.format.bold:
    default: op
  bungeechat.format.italic:
    default: op
  bungeechat.format.underline:
    default: op
  bungeechat.format.strikethrough:
    default: op
  bungeechat.format.magic:
    default: op
  
  bungeechat.message.toggle:
    default: op
  bungeechat.message:
    default: true
  bungeechat.message.override:
    default: op

  bungeechat.socialspy:
    default: op
    
commands:
  /nullcmd:
  
  tell:
    usage: /<command> <player> <message>
    aliases: [m,whisper,msg,t,w]
    description: Sends a message to <player>
    permission: bungeechat.message
    
  reply:
    usage: /<command> <message>
    aliases: [r]
    description: Sends a reply message to the last person you messaged, or that messaged you
    permission: bungeechat.message

  socialspy:
    usage: /<command>
    description: Toggles social spy
    permission: bungeechat.socialspy

  msgtoggle:
    usage: /<command>
    description: Toggles the ability for players to message you
    permission: bungeechat.message.toggle
  
  nickname:
    usage: /<command> [player] <name|off>
    description: Changes your nickname, or another players nickname. Setting the name "Off" will remove the nickname. Leaving the name blank will show their current name